@startuml

note as N1
  Singleton (シングルトン)
  <概要>
  システム内に存在するオブジェクトが1つであることを保証する。
  このパターンでは外部からのオブジェクトを生成を禁止する。
  システムの起動中はオブジェクト1つだけ制限したいときに使う
  <メリット>
  ・オブジェクトが1つしかないことが保証されている
end note

class FileFormatter {
  - singleton : Singleton
  - Singleton()
  + GetInstance() : Singleton
}

@enduml